---
title: "Informe estadístico - Pingüinos Palmer"
subtitle: "<b> Asignatura: </b> II4D3 - Estadística I <br>
          <b> Profesor: </b> Ing. Sebastián Blandón Londoño <br>
          Ingeniería Industrial <br>
          Facultad de Ciencias Empresariales <br> 
          <b> <i> Universidad Tecnológica de Pereira </i> </b>"
author:
  - name: Sebastián Blandón Londoño
    email: s.blandon@utp.edu.co
    url: https://www.linkedin.com/in/sebastian-blandon/
date: today
date-format: "YYYY/MM/DD"
lang: es-CO
theme:
  light: journal
  dark: darkly
format:
  html:
    author-title: "Autor"
    toc: true
    toc_levels: 4
    self-contained: true
    code-fold: true
    code-line-numbers: true
execute: 
  warning: false
---


# Preparación
## Carga de librerías
```{r}
library(dplyr) # Hace parte del tidyverse, se usa para transformar datos
library(ggplot2) # Hace parte del tidyverse, se usa para crear graficas
library(palmerpenguins) # Tiene los datos de los pinguinos
library(janitor) # Para limpiar los nombres del datos
library(openxlsx) # Gestionar archivos de Microsoft Office Excel
library(jsonlite) # Gestionar archivos json
library(skimr)
```

## Carga de datos
```{r}
datos <- palmerpenguins::penguins_raw %>% 
  clean_names()


#forma sin usar pipe




# Limpiar nombres
datos <- datos %>% 
  rename(
    delta_15_n = delta_15_n_o_oo,
    delta_13_c = delta_13_c_o_oo
  )
```

# Análisis preliminar
## Integridad por variable

**species**

- Cantidad de valores faltantes: ```r sum(is.na(datos$species))```
- Tipo de variable: ```r typeof(datos$species)```

**region**

- Cantidad de valores faltantes: ```r sum(is.na(datos$region))```
- Tipo de variable: ```r typeof(datos$region)```

**island**

**stage**

**individual_id**

**clutch_completion**

**date_egg**

**culmen_length_mm**

**culmen_depth_mm**

**flipper_length_mm**

**body_mass_g**

**sex**

**delta_15_n**

**delta_13_c**

**comments**
